apiVersion: v1
kind: Service
metadata:
  name: {{ include "terminal-server.fullname" . }}
  labels:
    {{- include "terminal-server.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "terminal-server.selectorLabels" . | nindent 4 }}
